# Tensor Basics
Numpy -> Torch Tensors

In [2]:
import torch
import numpy as np

torch.__version__

'1.9.0'

In [4]:
arr = np.array([1,2,3,4,5])

tensor = torch.from_numpy(arr)
tensor 

tensor([1, 2, 3, 4, 5])

<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Tensor Datatypes</a></h2>
<table style="display: inline-block">
<tr><th>TYPE</th><th>NAME</th><th>EQUIVALENT</th><th>TENSOR TYPE</th></tr>
<tr><td>32-bit integer (signed)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bit integer (signed)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bit integer (signed)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bit floating point</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bit floating point</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bit floating point</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bit integer (signed)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bit integer (unsigned)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table> 

# Tensor를 만드는 방법은 세개가 있는데,
- torch.from_numpy()
- torch.as_tensor()
- torch.tensor()
- 세가지 방법이 있다. **torch.from_numpy()**, **torch.as_tensor()**이 둘은 numpy와 메모리를 공유하기에 tensor가 변경되면 numpy도 변형됨. <br>
하지만 **torch.tensor()**은 카피본을 만듬

# Class constructors
- torch.Tensor()
- torch.FloatTensor()
- torch.LongTensor()
- etc...
- torch.tensor(data)와 torch.Tensor(data)를 쓰는데 약간의 차이점이 있다. torch.Tensor()은 torch.FloatTensor()의 alias이다.

In [5]:
data = np.array([1,2,3])

a = torch.Tensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [8]:
b = torch.tensor(data, dtype = torch.long)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


# Creating tensor from scratch
- torch.empty() 는 초기화되지(unitialized) 않은 텐서를 반환한다
- torch.zeros, torch.ones(initialized)

# Tensors from ranges
- torch.arange(start, end, step)   end를 포함하지 않음
- torch.linspace(start, end, steps)   end를 포함함


# Change type of Tensor
- use type

In [9]:
x = torch.tensor([8,9,-1], dtype = torch.int)

print(f'Old type: {x.type()}')

x = x.type(torch.int64)
print(f'New type: {x.type()}')

Old type: torch.IntTensor
New type: torch.LongTensor


# Random Number
- torch.rand(shape) : sampling from uniform(0,1)
- torch.randn(shape) : sampling from N(0,1)
- torch.randint(low,hight,shape) : sampling int from low high

# Random number with same size of tensor x
- torch.rand_like(tensor)
- torch.randn_likne(tensor)
- torch.randint_like(tensor, low, high)
- torch.zeros_like(tensor)
- torch.ones_like(tensor)

In [3]:
x = torch.zeros(2,5)
x2 = torch.randn_like(x)
x2

tensor([[-0.7908, -0.7156,  1.5054,  0.9501,  0.0084],
        [-0.5193,  0.7784, -0.8772,  0.5499, -1.3463]])